### ISSUE TITLE
Reintroduce test coverage for login views

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/auth#12]
**Problem:**
Currently the login view is not tested. Login is a critical part of the system so it should be covered. 

**Earlier work**
In an earlier version of the API project I managed to test a successful login by requesting the apps login endpoint with axios and following redirects while passing cookie information. You could look up the history of the ./test folder in the api project to see how this was handled.

**Scenarios**
- Should test for correct redirect to login page for authorization_code credentials
- Should test for properly submitted login credentials with login form
- Should test for correct redirect to client application after authentication success
- Should test for correct login error handling

**Comment by peterpolman** [comment]
Earlier authorization_code grant login flow https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts

**Comment by peterpolman** [comment]
An explanation of what the various requests simulate:

Initial authorization request from client:
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L20-L36

POST on login form: 
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L39-L49

Redirect to interaction:
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L52

Redirect to consent page (auto skipped in UI):
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L56

Redirect to client with auth code:
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L61-L62

POST on /token to obtain access token:
https://github.com/thxprotocol/api/blob/d0f03533901ad4c919a66a3684992d42dcd6b704/test/e2e/lib/authorizationCode.ts#L63

**Comment by GarfDev** [comment]
PR: https://github.com/thxprotocol/auth/pull/23
