### ISSUE TITLE
Implement MFA for accounts

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/auth#48]
Implementation of Google Authenticator MFA (probably Google Identity solutions) in the authorisation server flow. 

Acceptance Criteria
1. Use Google Authenticator or a popular alternative (discuss if other than GA)
2. User should be allowed to enable this in both THX Wallet and Dashboard
3. User should be forced to provide MFA input when activated for account

**Comment by GarfDev** [comment]
[](https://auth0.com/blog/from-theory-to-practice-adding-two-factor-to-node-dot-js/)### Today work

- Implement MFA (TOTP) Authentication flow
- Toggle option for `dashboard` and `wallet`  app

### Preparation

- [x]  Research about `interactionFinished` of OIDC
    - It can merge with the last submission or information.

### Breakdown

- [ ]  Implement `setup` route that returning QR code
    - [ ]  Implement controller in `auth`
    - [ ]  Implement setup page in `dashboard` and `wallet`
- [ ]  Implement shared code input for `auth` login page return

Rely on the following documentations

- [https://auth0.com/blog/from-theory-to-practice-adding-two-factor-to-node-dot-js/[](https://betterprogramming.pub/how-to-implement-two-factor-authentication-using-node-js-and-vue-3-1029745e06fd)](https://auth0.com/blog/from-theory-to-practice-adding-two-factor-to-node-dot-js/)
- [https://betterprogramming.pub/how-to-implement-two-factor-authentication-using-node-js-and-vue-3-1029745e06fd](https://betterprogramming.pub/how-to-implement-two-factor-authentication-using-node-js-and-vue-3-1029745e06fd)

**Comment by GarfDev** [comment]
Implemented in following PRs:
**Wallet**: https://github.com/thxprotocol/wallet/pull/59/files
**Dashboard**: https://github.com/thxprotocol/dashboard/pull/18
**Auth**: https://github.com/thxprotocol/auth/pull/54

@peterpolman
