### ISSUE TITLE
Implement Airtable API for account email storage

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/auth#51]
Store `account.email` and `account.createdAt` in Airtable: "Pipeline: Signups".

Base: https://airtable.com/appk2Xzy9HePlayC7/api/docs#curl/table:pipeline_colon_%20signups
Docs: https://airtable.com/api

**Comment by miesz-ko** [comment]
@GarfDev @peterpolman when we create this, is it possible to get the last 3 weeks of data imported?

**Comment by peterpolman** [comment]
@GarfDev probably add a migration for this? Or run a script once?

**Comment by peterpolman** [comment]
@miesz-ko Imported verified (non temp wallet) accounts into Airtable. All new verified accounts will also be inserted there.
