### ISSUE TITLE
Move skins resource to REST API

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/auth#83]
> I guess its more that I dont want to pollute the Auth project with other responsibilities than auth and account related stuff. And when moving that skins resource to the api project, we will only have to maintain 1 upload endpoint.

**Comment by GarfDev** [comment]
Closing this issue with following PRs:
[API] https://github.com/thxprotocol/api/pull/323
[AUTH] https://github.com/thxprotocol/auth/pull/88
[DASHBOARD] https://github.com/thxprotocol/dashboard/pull/60
